import assert from "node:assert/strict";
import test from "node:test";
import { buildPolicyDecisionUsageEvent, evaluatePolicyEngine as evaluatePolicy, listPolicyActions, type PolicyEngineEvaluationInput as PolicyEvaluationInput } from "@hallederiz/domain";
import { evaluatePolicyEngineForContext } from "../shared/policy-engine-runtime";
import { evaluateRoutePolicy } from "../shared/policy-bridge";
import type { RequestContext } from "../shared/request-context";
function baseInput(overrides: Partial<PolicyEvaluationInput> = {}): PolicyEvaluationInput { const actionKey = overrides.action?.actionKey ?? "platform.customers.read"; return { subject: { userId: "user_admin", tenantId: "tenant_1", roles: ["admin"], permissions: ["*"], authMode: "session", channel: "api", sessionRisk: "low" }, resource: { resourceType: "customer", tenantId: "tenant_1" }, action: { actionKey, actionType: overrides.action?.actionType ?? "read", criticality: overrides.action?.criticality ?? "low", requiresApproval: overrides.action?.requiresApproval, idempotencyRequired: overrides.action?.idempotencyRequired, auditRequired: overrides.action?.auditRequired }, context: { requestId: "req_policy_test", tenantId: "tenant_1", source: "api", environment: "development", persistenceMode: "demo", channel: "api" }, ...overrides }; }
function baseContext(permissions: string[] = ["*"]): RequestContext { return { tenantId: "tenant_1", userId: "user_admin", persistenceMode: "demo", isAuthenticated: true, roles: ["admin"], permissions }; }
test("policy engine denies unknown actions", () => { const decision = evaluatePolicy(baseInput({ action: { actionKey: "platform.unknown", actionType: "execute", criticality: "critical" } })); assert.equal(decision.effect, "deny"); assert.ok(decision.reasons.includes("unknown_action")); });
test("policy engine denies tenant mismatch and missing tenant", () => { const mismatch = evaluatePolicy(baseInput({ resource: { resourceType: "customer", tenantId: "tenant_other" } })); assert.equal(mismatch.effect, "deny"); assert.ok(mismatch.reasons.includes("tenant_mismatch")); const missing = evaluatePolicy(baseInput({ context: { ...baseInput().context, tenantId: "" } })); assert.equal(missing.effect, "deny"); assert.ok(missing.reasons.includes("missing_tenant_id")); });
test("policy engine denies missing permission and allows low-risk read with permission", () => { const denied = evaluatePolicy(baseInput({ subject: { ...baseInput().subject, permissions: [] } })); assert.equal(denied.effect, "deny"); assert.ok(denied.reasons.includes("required_permission_missing")); const allowed = evaluatePolicy(baseInput({ subject: { ...baseInput().subject, permissions: ["customers.read"] } })); assert.equal(allowed.effect, "allow"); });
test("critical write actions require approval even with permission", () => { const decision = evaluatePolicy(baseInput({ action: { actionKey: "platform.settings.update", actionType: "write", criticality: "critical" }, subject: { ...baseInput().subject, permissions: ["platform.settings.write"] } })); assert.equal(decision.effect, "require_approval"); assert.equal(decision.obligations.requireApproval, true); assert.equal(decision.obligations.requireAuditTimeline, true); });
test("AI critical execute remains dry-run or approval gated", () => { const decision = evaluatePolicy(baseInput({ action: { actionKey: "platform.ai.execute", actionType: "ai_execute", criticality: "critical" }, subject: { ...baseInput().subject, permissions: ["ai.actions.write"], channel: "api" }, context: { ...baseInput().context, source: "ai", channel: "api" } })); assert.equal(decision.effect, "dry_run_only"); assert.ok(decision.reasons.includes("ai_critical_execution_requires_human_approval")); assert.equal(decision.obligations.requireHumanReview, true); });
test("worker execution requires approved context idempotency and audit metadata", () => { const input = baseInput({ action: { actionKey: "worker.approval.dispatch", actionType: "execute", criticality: "critical" }, subject: { ...baseInput().subject, permissions: ["approvals.execute"], channel: "worker" }, resource: { resourceType: "approval_execution", tenantId: "tenant_1" }, context: { ...baseInput().context, source: "worker", channel: "worker" } }); const denied = evaluatePolicy(input); assert.equal(denied.effect, "deny"); assert.ok(denied.reasons.includes("worker_approved_context_required")); assert.ok(denied.reasons.includes("worker_idempotency_key_required")); const allowed = evaluatePolicy({ ...input, approval: { approved: true, approvalRequestId: "apr_1" }, idempotencyKey: "idem_1", auditMetadataPresent: true, timelineMetadataPresent: true }); assert.equal(allowed.effect, "allow"); });
test("WhatsApp approval command requires channel constraints", () => { const input = baseInput({ action: { actionKey: "platform.whatsapp.approval_command", actionType: "approve", criticality: "critical" }, subject: { ...baseInput().subject, permissions: ["approvals.approve"], channel: "whatsapp" }, resource: { resourceType: "approval", tenantId: "tenant_1" }, context: { ...baseInput().context, source: "whatsapp", channel: "whatsapp" } }); const denied = evaluatePolicy(input); assert.equal(denied.effect, "deny"); assert.ok(denied.obligations.requireChannelWindow); assert.ok(denied.reasons.includes("channel_signature_required")); const allowed = evaluatePolicy({ ...input, channelPolicy: { signatureVerified: true, approvalTokenVerified: true, phoneVerified: true, withinChannelWindow: true }, idempotencyKey: "wa_idem_1" }); assert.equal(allowed.effect, "allow"); });
test("production uncertain fallback denies", () => { const decision = evaluatePolicy(baseInput({ context: { ...baseInput().context, environment: "production", persistenceMode: "demo" }, fallbackCertainty: "uncertain" })); assert.equal(decision.effect, "deny"); assert.ok(decision.reasons.includes("production_persistence_mode_uncertain")); });
test("action registry entries include required safety fields", () => { const actions = listPolicyActions(); assert.ok(actions.length >= 18); for (const action of actions) { assert.ok(action.actionKey); assert.ok(action.description); assert.ok(action.requiredPermissions.length > 0); assert.ok(action.allowedSources.length > 0); assert.equal(typeof action.auditRequired, "boolean"); assert.equal(typeof action.idempotencyRequired, "boolean"); } });
test("policy bridge maps request context without weakening existing guard assumptions", () => { const context = baseContext(["platform.settings.write"]); const decision = evaluateRoutePolicy(context, { actionKey: "platform.settings.update" }); assert.equal(decision.decision, "require_approval"); assert.equal(decision.actionKey, "platform.settings.update"); assert.ok((decision as { policyEngine?: unknown }).policyEngine); const denied = evaluatePolicyEngineForContext(baseContext([]), { actionKey: "platform.settings.update" }); assert.equal(denied.effect, "deny"); assert.ok(denied.reasons.includes("required_permission_missing")); });
test("policy usage obligations can create tenant usage event metadata", () => { const input = baseInput({ action: { actionKey: "platform.ai.propose", actionType: "ai_propose", criticality: "low" }, subject: { ...baseInput().subject, permissions: ["ai.actions.write"] } }); const decision = evaluatePolicy(input); const usageEvent = buildPolicyDecisionUsageEvent(decision, input.subject, input.context); assert.ok(usageEvent); assert.equal(usageEvent?.tenantId, "tenant_1"); assert.equal(usageEvent?.eventType, "ai_request"); assert.equal(usageEvent?.metadata?.actionKey, "platform.ai.propose"); });
