import type { ActionRegistryEntry } from "@hallederiz/types";

export const actionRegistry: readonly ActionRegistryEntry[] = [
  {
    actionKey: "customer.read",
    description: "Cari okuma",
    requiredPermissions: ["customer.read", "customers.read"],
    requiredFeature: "core.customer",
    requiredModule: "core",
    isMutation: false,
    isCritical: false,
    approvalRequired: false,
    allowedActors: ["user", "ai", "system", "channel"],
    allowedChannels: ["crm_ui", "api", "worker", "whatsapp"],
    aiMode: "read_only",
    auditRequired: true,
    timelineRequired: false,
    idempotencyRequired: false
  },
  {
    actionKey: "platform.users.create",
    description: "Platform kullanici olusturma",
    requiredPermissions: ["platform.users.write", "users.manage"],
    requiredFeature: "core.approval",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.platform.users.create",
    allowedActors: ["user", "system"],
    allowedChannels: ["crm_ui", "api"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: false
  },
  {
    actionKey: "platform.settings.update",
    description: "Platform ayar guncelleme",
    requiredPermissions: ["platform.settings.write", "settings.manage"],
    requiredFeature: "core.approval",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.platform.settings.update",
    allowedActors: ["user", "system"],
    allowedChannels: ["crm_ui", "api"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: false
  },
  {
    actionKey: "order.create",
    description: "Siparis olusturma",
    requiredPermissions: ["order.create", "orders.write"],
    requiredFeature: "core.qop",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.order.create",
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: false
  },
  {
    actionKey: "platform.offers.create",
    description: "Teklif olusturma",
    requiredPermissions: ["offers.write"],
    requiredFeature: "core.qop",
    requiredModule: "core",
    isMutation: true,
    isCritical: false,
    approvalRequired: true,
    approvalPolicyKey: "approval.platform.offers.create",
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "platform.orders.create",
    description: "Siparis olusturma (platform)",
    requiredPermissions: ["orders.write", "order.create"],
    requiredFeature: "core.qop",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.platform.orders.create",
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "platform.payments.create",
    description: "Tahsilat olusturma (platform)",
    requiredPermissions: ["payments.write", "finance.payment.create"],
    requiredFeature: "core.qop",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.platform.payments.create",
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "finance.payment.create",
    description: "Tahsilat olusturma",
    requiredPermissions: ["finance.payment.create", "payments.write"],
    requiredFeature: "core.qop",
    requiredModule: "core",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.finance.payment.create",
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "request_approval",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "erp.sync.write",
    description: "ERP yazma senkronu",
    requiredPermissions: ["erp.sync.write", "erp.write", "integrations.write"],
    requiredFeature: "premium.erp",
    requiredModule: "erp",
    isMutation: true,
    isCritical: true,
    approvalRequired: true,
    approvalPolicyKey: "approval.erp.sync.write",
    allowedActors: ["user", "system"],
    allowedChannels: ["crm_ui", "api", "worker"],
    aiMode: "blocked",
    externalProviders: ["erp"],
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "channel.whatsapp.reply",
    description: "WhatsApp yanit gonderimi",
    requiredPermissions: ["channel.whatsapp.reply", "whatsapp.write", "integrations.write"],
    requiredFeature: "premium.whatsapp",
    requiredModule: "whatsapp",
    isMutation: true,
    isCritical: false,
    approvalRequired: false,
    allowedActors: ["user", "ai", "system", "channel"],
    allowedChannels: ["whatsapp", "crm_ui", "api"],
    aiMode: "draft",
    externalProviders: ["whatsapp"],
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: true
  },
  {
    actionKey: "ai.proposal.create",
    description: "AI proposal olusturma",
    requiredPermissions: ["ai.proposal.create", "ai.actions.write"],
    requiredFeature: "premium.ai.operator",
    requiredModule: "ai",
    isMutation: true,
    isCritical: false,
    approvalRequired: false,
    allowedActors: ["user", "ai", "system"],
    allowedChannels: ["crm_ui", "api"],
    aiMode: "propose",
    auditRequired: true,
    timelineRequired: true,
    idempotencyRequired: false
  }
] as const;

export function getActionRegistryEntry(actionKey: string): ActionRegistryEntry | undefined {
  return actionRegistry.find((entry) => entry.actionKey === actionKey);
}
