import type { PolicyActionRegistryEntry } from "./model";
function action(entry: PolicyActionRegistryEntry): PolicyActionRegistryEntry { return entry; }
export const policyActionRegistry = [
  action({ actionKey: "platform.customers.read", description: "Customer read access", actionType: "read", criticality: "low", requiredPermissions: ["customers.read", "customer.read"], defaultEffect: "allow", approvalRequired: false, auditRequired: false, timelineRequired: false, idempotencyRequired: false, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"] }),
  action({ actionKey: "platform.customers.create", description: "Customer create mutation", actionType: "write", criticality: "high", requiredPermissions: ["customers.write", "customer.create"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.customers.create" }),
  action({ actionKey: "platform.customers.update", description: "Customer update mutation", actionType: "write", criticality: "high", requiredPermissions: ["customers.write", "customer.update"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.customers.update" }),
  action({ actionKey: "platform.offers.read", description: "Offer read access", actionType: "read", criticality: "low", requiredPermissions: ["offers.read"], defaultEffect: "allow", approvalRequired: false, auditRequired: false, timelineRequired: false, idempotencyRequired: false, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"] }),
  action({ actionKey: "platform.offers.create", description: "Offer create mutation", actionType: "write", criticality: "medium", requiredPermissions: ["offers.write"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.offers.create" }),
  action({ actionKey: "platform.orders.read", description: "Order read access", actionType: "read", criticality: "low", requiredPermissions: ["orders.read"], defaultEffect: "allow", approvalRequired: false, auditRequired: false, timelineRequired: false, idempotencyRequired: false, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"] }),
  action({ actionKey: "platform.orders.create", description: "Order create mutation", actionType: "write", criticality: "critical", requiredPermissions: ["orders.write", "order.create"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.orders.create" }),
  action({ actionKey: "platform.payments.create", description: "Payment create mutation", actionType: "write", criticality: "critical", requiredPermissions: ["payments.write", "finance.payment.create"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.payments.create" }),
  action({ actionKey: "platform.documents.generate", description: "Document generation", actionType: "generate_document", criticality: "medium", requiredPermissions: ["documents.render", "documents.write"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "ai", "worker"], allowedChannels: ["web", "api", "worker"], usageEventType: "document_generation", approvalPolicyKey: "approval.platform.documents.generate" }),
  action({ actionKey: "platform.documents.send", description: "Document send action", actionType: "send_message", criticality: "high", requiredPermissions: ["documents.write", "integrations.write"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "worker"], allowedChannels: ["web", "api", "worker", "whatsapp", "email"], usageEventType: "channel_message", approvalPolicyKey: "approval.platform.documents.send" }),
  action({ actionKey: "platform.whatsapp.reply", description: "WhatsApp reply", actionType: "send_message", criticality: "medium", requiredPermissions: ["whatsapp.write", "integrations.write"], defaultEffect: "dry_run_only", approvalRequired: false, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api", "whatsapp", "ai"], allowedChannels: ["web", "api", "whatsapp"], usageEventType: "channel_message", channelPolicy: { requireSignature: true, requireChannelWindow: true, humanHandoffAllowed: true, autoReplyAllowed: false } }),
  action({ actionKey: "platform.whatsapp.approval_command", description: "WhatsApp approval command", actionType: "approve", criticality: "critical", requiredPermissions: ["approvals.approve", "approvals.write"], defaultEffect: "allow", approvalRequired: false, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["whatsapp"], allowedChannels: ["whatsapp"], usageEventType: "channel_message", channelPolicy: { requireSignature: true, requireApprovalToken: true, requireVerifiedPhone: true, requireChannelWindow: true, humanHandoffAllowed: true, autoReplyAllowed: false } }),
  action({ actionKey: "platform.whatsapp.action_request.confirm", description: "Operator confirms WhatsApp action request", actionType: "approve", criticality: "high", requiredPermissions: ["integrations.write", "approvals.write"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["api", "web"], allowedChannels: ["api", "web"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.whatsapp.action_request.confirm" }),
  action({ actionKey: "platform.ai.propose", description: "AI proposal generation", actionType: "ai_propose", criticality: "low", requiredPermissions: ["ai.actions.write", "ai.proposal.create"], defaultEffect: "allow", approvalRequired: false, auditRequired: true, timelineRequired: false, idempotencyRequired: false, allowedSources: ["web", "api", "ai"], allowedChannels: ["web", "api"], usageEventType: "ai_request" }),
  action({ actionKey: "platform.ai.execute", description: "AI execution attempt", actionType: "ai_execute", criticality: "critical", requiredPermissions: ["ai.actions.write"], defaultEffect: "dry_run_only", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["ai", "api"], allowedChannels: ["api"], usageEventType: "ai_request", approvalPolicyKey: "approval.platform.ai.execute" }),
  action({ actionKey: "platform.settings.update", description: "Platform settings update", actionType: "write", criticality: "critical", requiredPermissions: ["platform.settings.write", "settings.manage"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.settings.update" }),
  action({ actionKey: "platform.users.create", description: "Platform user create", actionType: "write", criticality: "critical", requiredPermissions: ["platform.users.write", "users.manage"], defaultEffect: "require_approval", approvalRequired: true, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["web", "api"], allowedChannels: ["web", "api"], usageEventType: "workflow_execution", approvalPolicyKey: "approval.platform.users.create" }),
  action({ actionKey: "worker.approval.dispatch", description: "Worker approval execution dispatch", actionType: "execute", criticality: "critical", requiredPermissions: ["approvals.execute"], defaultEffect: "allow", approvalRequired: false, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["worker", "system"], allowedChannels: ["worker", "system"], usageEventType: "workflow_execution" }),
  action({ actionKey: "worker.audit.timeline.writeback", description: "Worker audit/timeline writeback", actionType: "execute", criticality: "high", requiredPermissions: ["approvals.execute"], defaultEffect: "allow", approvalRequired: false, auditRequired: true, timelineRequired: true, idempotencyRequired: true, allowedSources: ["worker", "system"], allowedChannels: ["worker", "system"], usageEventType: "workflow_execution" })
] as const;
export function getPolicyAction(actionKey: string): PolicyActionRegistryEntry | undefined { return policyActionRegistry.find((action) => action.actionKey === actionKey); }
export function listPolicyActions(): PolicyActionRegistryEntry[] { return [...policyActionRegistry]; }
export function getAiVisiblePolicyActions() { return policyActionRegistry.filter((action) => action.allowedSources.includes("ai")).map(({ actionKey, description, actionType, criticality, defaultEffect, approvalRequired }) => ({ actionKey, description, actionType, criticality, defaultEffect, approvalRequired })); }
